//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocztaPolskaTrackerSoapClient.PocztaPolskaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sledzenie.pocztapolska.pl", ConfigurationName="PocztaPolskaService.SledzeniePortType")]
    public interface SledzeniePortType {
        
        // CODEGEN: Generating message contract since the operation wersja is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:wersja", ReplyAction="urn:wersjaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaResponse wersja(PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:wersja", ReplyAction="urn:wersjaResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaResponse> wersjaAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiPl", ReplyAction="urn:sprawdzPrzesylkiPlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlResponse sprawdzPrzesylkiPl(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiPl", ReplyAction="urn:sprawdzPrzesylkiPlResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlResponse> sprawdzPrzesylkiPlAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkePl", ReplyAction="urn:sprawdzPrzesylkePlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlResponse sprawdzPrzesylkePl(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkePl", ReplyAction="urn:sprawdzPrzesylkePlResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlResponse> sprawdzPrzesylkePlAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiOdDo", ReplyAction="urn:sprawdzPrzesylkiOdDoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoResponse sprawdzPrzesylkiOdDo(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiOdDo", ReplyAction="urn:sprawdzPrzesylkiOdDoResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoResponse> sprawdzPrzesylkiOdDoAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoRequest request);
        
        // CODEGEN: Generating message contract since the operation maksymalnaLiczbaPrzesylek is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:maksymalnaLiczbaPrzesylek", ReplyAction="urn:maksymalnaLiczbaPrzesylekResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekResponse maksymalnaLiczbaPrzesylek(PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:maksymalnaLiczbaPrzesylek", ReplyAction="urn:maksymalnaLiczbaPrzesylekResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekResponse> maksymalnaLiczbaPrzesylekAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylke", ReplyAction="urn:sprawdzPrzesylkeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeResponse sprawdzPrzesylke(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylke", ReplyAction="urn:sprawdzPrzesylkeResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeResponse> sprawdzPrzesylkeAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiOdDoPl", ReplyAction="urn:sprawdzPrzesylkiOdDoPlResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlResponse sprawdzPrzesylkiOdDoPl(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylkiOdDoPl", ReplyAction="urn:sprawdzPrzesylkiOdDoPlResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlResponse> sprawdzPrzesylkiOdDoPlAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:witaj", ReplyAction="urn:witajResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajResponse witaj(PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:witaj", ReplyAction="urn:witajResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajResponse> witajAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylki", ReplyAction="urn:sprawdzPrzesylkiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiResponse sprawdzPrzesylki(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sprawdzPrzesylki", ReplyAction="urn:sprawdzPrzesylkiResponse")]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiResponse> sprawdzPrzesylkiAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wersjaRequest {
        
        public wersjaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wersjaResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class wersjaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public wersjaResponse() {
        }
        
        public wersjaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Komunikat : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Przesylka[] przesylkiField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("przesylka")]
        public Przesylka[] przesylki {
            get {
                return this.przesylkiField;
            }
            set {
                this.przesylkiField = value;
                this.RaisePropertyChanged("przesylki");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Przesylka : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DanePrzesylki danePrzesylkiField;
        
        private string numerField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public DanePrzesylki danePrzesylki {
            get {
                return this.danePrzesylkiField;
            }
            set {
                this.danePrzesylkiField = value;
                this.RaisePropertyChanged("danePrzesylki");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string numer {
            get {
                return this.numerField;
            }
            set {
                this.numerField = value;
                this.RaisePropertyChanged("numer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class DanePrzesylki : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> dataNadaniaField;
        
        private bool dataNadaniaFieldSpecified;
        
        private string kodKrajuNadaniaField;
        
        private string kodKrajuPrzeznField;
        
        private string kodRodzPrzesField;
        
        private string krajNadaniaField;
        
        private string krajPrzeznField;
        
        private System.Nullable<float> masaField;
        
        private bool masaFieldSpecified;
        
        private string numerField;
        
        private string rodzPrzesField;
        
        private Jednostka urzadNadaniaField;
        
        private Jednostka urzadPrzeznField;
        
        private bool zakonczonoObslugeField;
        
        private bool zakonczonoObslugeFieldSpecified;
        
        private Zdarzenie[] zdarzeniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> dataNadania {
            get {
                return this.dataNadaniaField;
            }
            set {
                this.dataNadaniaField = value;
                this.RaisePropertyChanged("dataNadania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataNadaniaSpecified {
            get {
                return this.dataNadaniaFieldSpecified;
            }
            set {
                this.dataNadaniaFieldSpecified = value;
                this.RaisePropertyChanged("dataNadaniaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string kodKrajuNadania {
            get {
                return this.kodKrajuNadaniaField;
            }
            set {
                this.kodKrajuNadaniaField = value;
                this.RaisePropertyChanged("kodKrajuNadania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string kodKrajuPrzezn {
            get {
                return this.kodKrajuPrzeznField;
            }
            set {
                this.kodKrajuPrzeznField = value;
                this.RaisePropertyChanged("kodKrajuPrzezn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string kodRodzPrzes {
            get {
                return this.kodRodzPrzesField;
            }
            set {
                this.kodRodzPrzesField = value;
                this.RaisePropertyChanged("kodRodzPrzes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string krajNadania {
            get {
                return this.krajNadaniaField;
            }
            set {
                this.krajNadaniaField = value;
                this.RaisePropertyChanged("krajNadania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string krajPrzezn {
            get {
                return this.krajPrzeznField;
            }
            set {
                this.krajPrzeznField = value;
                this.RaisePropertyChanged("krajPrzezn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<float> masa {
            get {
                return this.masaField;
            }
            set {
                this.masaField = value;
                this.RaisePropertyChanged("masa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool masaSpecified {
            get {
                return this.masaFieldSpecified;
            }
            set {
                this.masaFieldSpecified = value;
                this.RaisePropertyChanged("masaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string numer {
            get {
                return this.numerField;
            }
            set {
                this.numerField = value;
                this.RaisePropertyChanged("numer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string rodzPrzes {
            get {
                return this.rodzPrzesField;
            }
            set {
                this.rodzPrzesField = value;
                this.RaisePropertyChanged("rodzPrzes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public Jednostka urzadNadania {
            get {
                return this.urzadNadaniaField;
            }
            set {
                this.urzadNadaniaField = value;
                this.RaisePropertyChanged("urzadNadania");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public Jednostka urzadPrzezn {
            get {
                return this.urzadPrzeznField;
            }
            set {
                this.urzadPrzeznField = value;
                this.RaisePropertyChanged("urzadPrzezn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool zakonczonoObsluge {
            get {
                return this.zakonczonoObslugeField;
            }
            set {
                this.zakonczonoObslugeField = value;
                this.RaisePropertyChanged("zakonczonoObsluge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zakonczonoObslugeSpecified {
            get {
                return this.zakonczonoObslugeFieldSpecified;
            }
            set {
                this.zakonczonoObslugeFieldSpecified = value;
                this.RaisePropertyChanged("zakonczonoObslugeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("zdarzenie")]
        public Zdarzenie[] zdarzenia {
            get {
                return this.zdarzeniaField;
            }
            set {
                this.zdarzeniaField = value;
                this.RaisePropertyChanged("zdarzenia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Jednostka : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SzczDaneJednostki daneSzczegoloweField;
        
        private string nazwaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public SzczDaneJednostki daneSzczegolowe {
            get {
                return this.daneSzczegoloweField;
            }
            set {
                this.daneSzczegoloweField = value;
                this.RaisePropertyChanged("daneSzczegolowe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
                this.RaisePropertyChanged("nazwa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class SzczDaneJednostki : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float dlGeogrField;
        
        private bool dlGeogrFieldSpecified;
        
        private GodzinyPracy godzinyPracyField;
        
        private string miejscowoscField;
        
        private string nrDomuField;
        
        private string nrLokaluField;
        
        private string pnaField;
        
        private float szerGeogrField;
        
        private bool szerGeogrFieldSpecified;
        
        private string ulicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public float dlGeogr {
            get {
                return this.dlGeogrField;
            }
            set {
                this.dlGeogrField = value;
                this.RaisePropertyChanged("dlGeogr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dlGeogrSpecified {
            get {
                return this.dlGeogrFieldSpecified;
            }
            set {
                this.dlGeogrFieldSpecified = value;
                this.RaisePropertyChanged("dlGeogrSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public GodzinyPracy godzinyPracy {
            get {
                return this.godzinyPracyField;
            }
            set {
                this.godzinyPracyField = value;
                this.RaisePropertyChanged("godzinyPracy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string miejscowosc {
            get {
                return this.miejscowoscField;
            }
            set {
                this.miejscowoscField = value;
                this.RaisePropertyChanged("miejscowosc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string nrDomu {
            get {
                return this.nrDomuField;
            }
            set {
                this.nrDomuField = value;
                this.RaisePropertyChanged("nrDomu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nrLokalu {
            get {
                return this.nrLokaluField;
            }
            set {
                this.nrLokaluField = value;
                this.RaisePropertyChanged("nrLokalu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string pna {
            get {
                return this.pnaField;
            }
            set {
                this.pnaField = value;
                this.RaisePropertyChanged("pna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public float szerGeogr {
            get {
                return this.szerGeogrField;
            }
            set {
                this.szerGeogrField = value;
                this.RaisePropertyChanged("szerGeogr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool szerGeogrSpecified {
            get {
                return this.szerGeogrFieldSpecified;
            }
            set {
                this.szerGeogrFieldSpecified = value;
                this.RaisePropertyChanged("szerGeogrSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string ulica {
            get {
                return this.ulicaField;
            }
            set {
                this.ulicaField = value;
                this.RaisePropertyChanged("ulica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class GodzinyPracy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GodzinyZUwagami dniRoboczeField;
        
        private GodzinyZUwagami niedzISwField;
        
        private GodzinyZUwagami sobotyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public GodzinyZUwagami dniRobocze {
            get {
                return this.dniRoboczeField;
            }
            set {
                this.dniRoboczeField = value;
                this.RaisePropertyChanged("dniRobocze");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public GodzinyZUwagami niedzISw {
            get {
                return this.niedzISwField;
            }
            set {
                this.niedzISwField = value;
                this.RaisePropertyChanged("niedzISw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public GodzinyZUwagami soboty {
            get {
                return this.sobotyField;
            }
            set {
                this.sobotyField = value;
                this.RaisePropertyChanged("soboty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class GodzinyZUwagami : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string godzinyField;
        
        private string uwagiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string godziny {
            get {
                return this.godzinyField;
            }
            set {
                this.godzinyField = value;
                this.RaisePropertyChanged("godziny");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string uwagi {
            get {
                return this.uwagiField;
            }
            set {
                this.uwagiField = value;
                this.RaisePropertyChanged("uwagi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Przyczyna : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kodField;
        
        private string nazwaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
                this.RaisePropertyChanged("nazwa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.sledzenie.pocztapolska.pl/xsd")]
    public partial class Zdarzenie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string czasField;
        
        private Jednostka jednostkaField;
        
        private string kodField;
        
        private bool konczaceField;
        
        private bool konczaceFieldSpecified;
        
        private string nazwaField;
        
        private Przyczyna przyczynaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string czas {
            get {
                return this.czasField;
            }
            set {
                this.czasField = value;
                this.RaisePropertyChanged("czas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public Jednostka jednostka {
            get {
                return this.jednostkaField;
            }
            set {
                this.jednostkaField = value;
                this.RaisePropertyChanged("jednostka");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool konczace {
            get {
                return this.konczaceField;
            }
            set {
                this.konczaceField = value;
                this.RaisePropertyChanged("konczace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool konczaceSpecified {
            get {
                return this.konczaceFieldSpecified;
            }
            set {
                this.konczaceFieldSpecified = value;
                this.RaisePropertyChanged("konczaceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
                this.RaisePropertyChanged("nazwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public Przyczyna przyczyna {
            get {
                return this.przyczynaField;
            }
            set {
                this.przyczynaField = value;
                this.RaisePropertyChanged("przyczyna");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiPl", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiPlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numer", IsNullable=true)]
        public string[] numer;
        
        public sprawdzPrzesylkiPlRequest() {
        }
        
        public sprawdzPrzesylkiPlRequest(string[] numer) {
            this.numer = numer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiPlResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiPlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat @return;
        
        public sprawdzPrzesylkiPlResponse() {
        }
        
        public sprawdzPrzesylkiPlResponse(PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkePl", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkePlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numer;
        
        public sprawdzPrzesylkePlRequest() {
        }
        
        public sprawdzPrzesylkePlRequest(string numer) {
            this.numer = numer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkePlResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkePlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Przesylka @return;
        
        public sprawdzPrzesylkePlResponse() {
        }
        
        public sprawdzPrzesylkePlResponse(PocztaPolskaTrackerSoapClient.PocztaPolskaService.Przesylka @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiOdDo", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiOdDoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numer", IsNullable=true)]
        public string[] numer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string odDnia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doDnia;
        
        public sprawdzPrzesylkiOdDoRequest() {
        }
        
        public sprawdzPrzesylkiOdDoRequest(string[] numer, string odDnia, string doDnia) {
            this.numer = numer;
            this.odDnia = odDnia;
            this.doDnia = doDnia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiOdDoResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiOdDoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat @return;
        
        public sprawdzPrzesylkiOdDoResponse() {
        }
        
        public sprawdzPrzesylkiOdDoResponse(PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class maksymalnaLiczbaPrzesylekRequest {
        
        public maksymalnaLiczbaPrzesylekRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="maksymalnaLiczbaPrzesylekResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class maksymalnaLiczbaPrzesylekResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        public int @return;
        
        public maksymalnaLiczbaPrzesylekResponse() {
        }
        
        public maksymalnaLiczbaPrzesylekResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylke", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numer;
        
        public sprawdzPrzesylkeRequest() {
        }
        
        public sprawdzPrzesylkeRequest(string numer) {
            this.numer = numer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkeResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Przesylka @return;
        
        public sprawdzPrzesylkeResponse() {
        }
        
        public sprawdzPrzesylkeResponse(PocztaPolskaTrackerSoapClient.PocztaPolskaService.Przesylka @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiOdDoPl", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiOdDoPlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numer", IsNullable=true)]
        public string[] numer;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string odDnia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string doDnia;
        
        public sprawdzPrzesylkiOdDoPlRequest() {
        }
        
        public sprawdzPrzesylkiOdDoPlRequest(string[] numer, string odDnia, string doDnia) {
            this.numer = numer;
            this.odDnia = odDnia;
            this.doDnia = doDnia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiOdDoPlResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiOdDoPlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat @return;
        
        public sprawdzPrzesylkiOdDoPlResponse() {
        }
        
        public sprawdzPrzesylkiOdDoPlResponse(PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="witaj", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class witajRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string imie;
        
        public witajRequest() {
        }
        
        public witajRequest(string imie) {
            this.imie = imie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="witajResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class witajResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @return;
        
        public witajResponse() {
        }
        
        public witajResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylki", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("numer", IsNullable=true)]
        public string[] numer;
        
        public sprawdzPrzesylkiRequest() {
        }
        
        public sprawdzPrzesylkiRequest(string[] numer) {
            this.numer = numer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sprawdzPrzesylkiResponse", WrapperNamespace="http://sledzenie.pocztapolska.pl", IsWrapped=true)]
    public partial class sprawdzPrzesylkiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sledzenie.pocztapolska.pl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat @return;
        
        public sprawdzPrzesylkiResponse() {
        }
        
        public sprawdzPrzesylkiResponse(PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SledzeniePortTypeChannel : PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SledzeniePortTypeClient : System.ServiceModel.ClientBase<PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType>, PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType {
        
        public SledzeniePortTypeClient() {
        }
        
        public SledzeniePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SledzeniePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SledzeniePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SledzeniePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.wersja(PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaRequest request) {
            return base.Channel.wersja(request);
        }
        
        public string wersja() {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaRequest();
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).wersja(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.wersjaAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaRequest request) {
            return base.Channel.wersjaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaResponse> wersjaAsync() {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.wersjaRequest();
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).wersjaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkiPl(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlRequest request) {
            return base.Channel.sprawdzPrzesylkiPl(request);
        }
        
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat sprawdzPrzesylkiPl(string[] numer) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlRequest();
            inValue.numer = numer;
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkiPl(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkiPlAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlRequest request) {
            return base.Channel.sprawdzPrzesylkiPlAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlResponse> sprawdzPrzesylkiPlAsync(string[] numer) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiPlRequest();
            inValue.numer = numer;
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkiPlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkePl(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlRequest request) {
            return base.Channel.sprawdzPrzesylkePl(request);
        }
        
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Przesylka sprawdzPrzesylkePl(string numer) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlRequest();
            inValue.numer = numer;
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkePl(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkePlAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlRequest request) {
            return base.Channel.sprawdzPrzesylkePlAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlResponse> sprawdzPrzesylkePlAsync(string numer) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkePlRequest();
            inValue.numer = numer;
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkePlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkiOdDo(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoRequest request) {
            return base.Channel.sprawdzPrzesylkiOdDo(request);
        }
        
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat sprawdzPrzesylkiOdDo(string[] numer, string odDnia, string doDnia) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoRequest();
            inValue.numer = numer;
            inValue.odDnia = odDnia;
            inValue.doDnia = doDnia;
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkiOdDo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkiOdDoAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoRequest request) {
            return base.Channel.sprawdzPrzesylkiOdDoAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoResponse> sprawdzPrzesylkiOdDoAsync(string[] numer, string odDnia, string doDnia) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoRequest();
            inValue.numer = numer;
            inValue.odDnia = odDnia;
            inValue.doDnia = doDnia;
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkiOdDoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.maksymalnaLiczbaPrzesylek(PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekRequest request) {
            return base.Channel.maksymalnaLiczbaPrzesylek(request);
        }
        
        public int maksymalnaLiczbaPrzesylek() {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekRequest();
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).maksymalnaLiczbaPrzesylek(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.maksymalnaLiczbaPrzesylekAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekRequest request) {
            return base.Channel.maksymalnaLiczbaPrzesylekAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekResponse> maksymalnaLiczbaPrzesylekAsync() {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.maksymalnaLiczbaPrzesylekRequest();
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).maksymalnaLiczbaPrzesylekAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylke(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeRequest request) {
            return base.Channel.sprawdzPrzesylke(request);
        }
        
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Przesylka sprawdzPrzesylke(string numer) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeRequest();
            inValue.numer = numer;
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylke(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkeAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeRequest request) {
            return base.Channel.sprawdzPrzesylkeAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeResponse> sprawdzPrzesylkeAsync(string numer) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkeRequest();
            inValue.numer = numer;
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkiOdDoPl(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlRequest request) {
            return base.Channel.sprawdzPrzesylkiOdDoPl(request);
        }
        
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat sprawdzPrzesylkiOdDoPl(string[] numer, string odDnia, string doDnia) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlRequest();
            inValue.numer = numer;
            inValue.odDnia = odDnia;
            inValue.doDnia = doDnia;
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkiOdDoPl(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkiOdDoPlAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlRequest request) {
            return base.Channel.sprawdzPrzesylkiOdDoPlAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlResponse> sprawdzPrzesylkiOdDoPlAsync(string[] numer, string odDnia, string doDnia) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiOdDoPlRequest();
            inValue.numer = numer;
            inValue.odDnia = odDnia;
            inValue.doDnia = doDnia;
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkiOdDoPlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.witaj(PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajRequest request) {
            return base.Channel.witaj(request);
        }
        
        public string witaj(string imie) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajRequest();
            inValue.imie = imie;
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).witaj(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.witajAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajRequest request) {
            return base.Channel.witajAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajResponse> witajAsync(string imie) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.witajRequest();
            inValue.imie = imie;
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).witajAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiResponse PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylki(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiRequest request) {
            return base.Channel.sprawdzPrzesylki(request);
        }
        
        public PocztaPolskaTrackerSoapClient.PocztaPolskaService.Komunikat sprawdzPrzesylki(string[] numer) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiRequest();
            inValue.numer = numer;
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiResponse retVal = ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylki(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiResponse> PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType.sprawdzPrzesylkiAsync(PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiRequest request) {
            return base.Channel.sprawdzPrzesylkiAsync(request);
        }
        
        public System.Threading.Tasks.Task<PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiResponse> sprawdzPrzesylkiAsync(string[] numer) {
            PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiRequest inValue = new PocztaPolskaTrackerSoapClient.PocztaPolskaService.sprawdzPrzesylkiRequest();
            inValue.numer = numer;
            return ((PocztaPolskaTrackerSoapClient.PocztaPolskaService.SledzeniePortType)(this)).sprawdzPrzesylkiAsync(inValue);
        }
    }
}
